name: x_qrcode
description: X-QRCode

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.3+1
  flutter_auth0: 0.5.0
  flutter_secure_storage: 3.3.1+1
  flutter_dotenv: ^2.1.0
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  signature: ^3.0.0
  barcode_scan: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/logo_xqrcode.svg
    - images/logo_pse.png
    - images/logo_mark.svg
    - .env
    - images/disconnect.svg
  fonts:
    - family: FuturaNext
      fonts:
        - asset: fonts/FuturaNext-Book.ttf
